---
# Create the file (/etc/docker/daemon.json) used to configure Docker daemon.
# For details, see https://docs.docker.com/config/daemon/systemd/
write_files:
  - path: "/etc/docker/daemon.json"
    permissions: "0644"
    owner: root:root
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {"max-size": "5000m", "max-file": "2"}
      }