#cloud-config
package_update: true

packages:
  - nfs-common

runcmd:
  - mkdir -p /etc/docker
  - |
    cat > /etc/docker/daemon.json <<EOF
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "5000m",
        "max-file": "1"
      },
      "default-ulimits": {
        "nofile": {
          "Soft": 1048576,
          "Hard": 1048576,
          "Name": "nofile"
        }
      }
    }
    EOF
  - chmod 0644 /etc/docker/daemon.json
  - sed -i -e 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config