#cloud-config
package_update: true

packages:
  - nfs-common

write_files:
  - path: "/etc/docker/daemon.json"
    permissions: "0644"
    owner: root:root
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {"max-size": "5000m", "max-file": "1"},
        "default-ulimits": {"nofile": {"Soft": 1048576, "Hard": 1048576, "Name": "nofile"}}
      }

runcmd:
 - sed -i -e 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
