#cloud-config
package_update: true

packages:
  - nfs-common

write_files:
  - path: "/etc/docker/daemon.json"
    permissions: "0644"
    owner: root:root
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {"max-size": "5000m", "max-file": "1"},
        "default-ulimits": {"nofile": {"Soft": 640000, "Hard": 640000, "Name": "nofile"}}
      }
