name: Validate Terraform
on:
  pull_request:
    branches:
    - main
jobs:
  terraform-validate:
    runs-on: ["self-hosted", "k8s-prod"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Validate Terraform configuration
      uses: devops-infra/action-terraform-validate@v0.3.1
